== AUDIENCE 5. Decision makers

=== Constituent segments

*	National government ministry and agency officials
*	Research funding agencies
*	Intergovernmental convention officials and national delegates
*	Global foundations

=== Primary communication needs 

*	Convincing leaders that GBIF’s mission coincides with high-priority policy objectives and global commitments
*	Demonstrating that investment in GBIF (globally and in-country) represents a cost-effective means of supporting those objectives and commitments
*	Persuasion that GBIF is not in competition with other biodiversity-related initiatives but rather supports and complements them.

GBIF’s future depends in part on remaining useful and relevant to a relatively small number of decision makers in key policymaking and funding positions. If these funders and executives are unconvinced of GBIF’s utility value, it will not survive even if all other aspects of its communication strategy are successful. The communication needs of this group are characterized by brevity and clarity; messages must be conveyed strategically, succinctly and persuasively, and often delivered opportunistically and at short notice. Decision makers are the primary consumers of the ‘elevator pitch’—the 30-second explanation of GBIF’s value that can influence participation or withdrawal of support from governments and agencies. 

Communications with this group should convince them to conclude that GBIF supports the objectives and obligations already on their list of priorities. Such priorities may include, for example, a country’s treaty obligations through the Convention on Biological Diversity (CBD) or national commitments to open access policies for data and science. They may also relate to objectives less directly connected to conservation or biological research per se, as with goals relating to human development, such as human health, food security and economic livelihoods.

In addition to convincing this audience of GBIF’s relevance, communication with them must also articulate the cost-effectiveness of investing in both the global infrastructure and the activities of the national node to support the development and maintenance of data-driven evidence for their goals and objectives.

Finally, engaging this audience needs to pre-empt questions about any perceived duplication between GBIF and other biodiversity-related information initiatives, stressing its complementarity with and, indeed, direct involvement in institutions such as the CBD, the Intergovernmental Platform on Biodiversity and Ecosystem Services (IPBES) and the Group on Earth Observations Biodiversity Observation Network (GEO BON). 

=== Key messages 

GBIF is particularly valuable to decision makers because it:

* Supports the information requirements for meeting national and global commitments, including biodiversity-related conventions and sustainable development goals
*	Leverages national, regional and global investment in scientific research by enabling cost-effective discovery and re-use of existing biodiversity data
*	Complements other biodiversity-related initiatives by providing data foundations for a wide range of studies, projects and applications
*	Helps to fulfill commitments to improve transparency and open access to scientific data 
*	Supports applied research relevant to policy decisions across a range of issues of primary economic and social importance, including food security, agricultural livelihoods, disease risk and the impacts of climate change. 
