== AUDIENCE 1. The GBIF network

=== Constituent segments

* Node managers, staff, and governance members
* Heads of delegation and other Governing Board delegates
*	Advisory committee members
*	Secretariat staff and contractors
*	Relevant staff in GBIF affiliate organizations and those with memoranda of cooperation with GBIF Secretariat

=== Primary communication needs

* Clear information on how to participate effectively in GBIF and obtain the benefits arising from participation
*	Resources to help communicate onwards the means and benefits of participation to relevant stakeholders
*	Efficient mechanisms for two-way communication to ensure rich sharing of information across the community and to external audiences 

This audience may be described as GBIF ‘insiders’ or ‘family’: those who work (explicitly or implicitly) to implement GBIF’s mission, strategic plans and work programmes, either as signatories to the MoU, memoranda of cooperation or under contracts. It is a diverse group as reflected by the constituent segments, but each constituency shares some critical communication needs. 

Broadly speaking, they all need to understand precisely why they are involved with GBIF, how they can participate most effectively and what the benefits they obtain (or can obtain) from such engagement. In addition, they need to be equipped with the relevant information resources to communicate onwards GBIF’s activities and value to their own wide ranging stakeholders. 

To maintain and grow the GBIF network, communications must directly address and engage this critical audience, as a means of sustaining a shared sense of purpose for GBIF and gluing the community together. The GBIF network has a general need for information that clearly and accurately describes the enterprise across all levels and scales of its activities and organization, from formal characterizations of its structure and governance to the technical details of data standards and publication. 

Communications within the GBIF network must flow in both directions: not only ensuring that each segment of this audience has timely access to relevant information, but also providing efficient mechanisms for disseminating network activities to wider external communities and audiences, with the Secretariat coordinating this bidirectional flow of communication. 

The entire GBIF network performs the work of outreach to national or thematic stakeholders, so all members have an interest in reducing communication-related barriers to participation for the other audiences (data holders, biological knowledge experts, data users, decision makers and public stakeholders). Each segment of the GBIF network stands to benefit from the creation of an extended set of information products that systematically offers answers to questions such as: ‘Why are we in GBIF? How do I participate most effectively? How do I communicate the benefits of GBIF to those whose support is essential for the future of the network? How do we make GBIF better?’

By providing GBIF network members with a clear framework, shared vocabulary and consistent materials that tell their collective story—why they are engaged in GBIF, how that engagement works, and what tools and techniques enable it— the combined efforts of the network will be better understood, recognized and valued. Meeting the communication needs of this audience is a critical foundation towards long-term sustainability for the GBIF collaborative enterprise and the ideals it encapsulates. 

=== Key messages 

GBIF is particularly valuable to network members because it:

*	Enables them to use GBIF’s collaborative mechanisms to solve problems and generate positive impacts
*	Offers common tools, practices and information resources to help meet national or organizational needs for mobilizing and managing biodiversity data, including through development of national or thematic web portals
*	Enables the integration of data from national and regional sources with other relevant data published elsewhere
*	Offers researchers within countries or organizations a cost-effective means of accessing all available data on the occurrence of species 
*	Supports national commitments to conserve and sustain national biodiversity resources and to promote open access to scientific data
*	Places the network’s activities within a meaningful global context
