== Background

Since its establishment in 2001, GBIF has established an effective infrastructure that delivers primary biodiversity data and multiplies the impact of hundreds of other organizations and initiatives. However, the influence and extent of GBIF’s global network remain relatively underappreciated.

To capitalize on its successes to date, and to fulfil the needs of the biodiversity science and policy communities, the GBIF community must continuously refine and refocus its efforts to communicate the fundamental value of this unique and highly effective enterprise to each of the audiences it serves. This task is best conducted with clear articulation of those audiences, how and why they should support or participate in GBIF, and how best to deliver on the promise that inspired the establishment of GBIF.

The challenge of communicating clearly about GBIF begins even with the simple description of what it is and what it does. This is in part because GBIF is not a formal, treaty-based institution, but the product of a voluntary collaboration between Participant countries and organizations, with an international coordinating body (the Secretariat) funded jointly by those Participants. So how does one best describe GBIF?

More than a formal structure or entity, GBIF is a pledge towards common actions and goals. A pledge to make biodiversity data freely and openly available. A pledge to enable their constructive use and application across relevant research and policy realms. A pledge to continuously improve and increase these data over time. And a pledge to be at the forefront of building a culture of open data and transparency.

The body of individuals and institutions coalescing around this pledge, even if it is not a legally defined institution, increasingly sees itself as a community with a shared purpose, vision and collective identity. Strong communication with relevant audiences lies at the heart of its future success.

This document summarizes how GBIF can give structure to its communication activities within its present community, while seeking to expand in the coming years. The strategy’s key components include:

* GBIF’s value proposition
*	An message-oriented use-case analysis and grouping of GBIF’s audiences
*	Segmentation of audiences, along with messaging aligned with the needs and interests of these audiences
*	A discussion of the channels available to reach these target segments

This is a communication strategy for the whole GBIF community. While each GBIF Participant will have specific communication needs, the analysis of audiences and messages outlined here is relevant both to global communication through the Secretariat, and to a large portion of national activities through nodes and participating institutions. 

The strategy provides the means for the Secretariat, in collaboration with the GBIF community, to set priorities for developing new documentation and for initiating translations into key languages. This needs-based assessment and prioritization helps to ensure that GBIF’s communication with all audiences is consistently and effectively disseminated. It also provides a flexible, long-term framework for adjusting the strategy over time and improving its relevance to the communities it intends to cultivate and grow.
