== AUDIENCE 6. Public stakeholders

=== Constituent segments

*	Early-career scientists
*	Educators (professors and teachers)
*	University students in biodiversity, environment and life sciences 
*	School students (tertiary, secondary, primary)
*	Wildlife enthusiasts
*	Environmentally engaged individuals
*	The wider software developer community

The audiences listed in the earlier part of this strategy each have distinct communication requirements that are indispensible to the GBIF’s global mission. These audiences extend into other groups for whom communication from the GBIF Secretariat may be less essential, but who nevertheless merit attention in this strategy because of the indirect or long-term benefits of raising awareness of GBIF. The Participants in the GBIF network also often have an interest in directly engaging these groups in order to build and consolidate support for their national, regional or thematic activities.

This broad audience of public stakeholders includes early-career scientists, educators and students (particularly in the life sciences), wildlife enthusiasts, and environmentally engaged citizens. These groups may have some interest in and awareness of GBIF.org as a freely available source of global data on biodiversity; however, their contact is more likely be with those sites aimed directly at lay audiences, some of which contribute data through GBIF or make use of GBIF as a data source. Portals developed by GBIF Participants also serve the function of informing local constituencies about the species that occur in their countries, regions and localities. 

Engagement with these groups is probably most effective in the context of citizen science (see also Audience Group 2 – Data holders). Several GBIF nodes have initiated highly successful campaigns to engage non-professional participants to generate data, for example, through ’bioblitz’ events and crowd-sourced digitization and curation of specimen data. Communication in the context of such activities shows individuals that their enthusiasm for wildlife can produce valuable scientific evidence that benefits the whole community while offering recognition for individual observers or collectors. Such communications provide value by expanding constituencies of support for global and national activities through GBIF .

A final set of stakeholders is the wider group of software developers that shows interest and appreciation of the open-access research infrastructure developed through GBIF to meet the challenges of biodiversity informatics. It is important to stay engaged with members of this specialist community, even if engaging them appears not to bring direct or immediate benefits to the GBIF mission. Their recognition of GBIF’s activities can help ensure that GBIF’s work is understood and appreciated as an important example of trends and developments across the wider technology and informatics sectors.

=== Key messages 

GBIF is particularly valuable to public stakeholders because it:

*	Establishes a foundation for greater knowledge about biodiversity worldwide
*	Offers opportunities to explore the global body of evidence about life on earth 
*	Promotes a culture of transparency, open access and evidence-based decision-making with benefits to all
*	Offers examples of innovative solutions for informatics and research infrastructure that are relevant and applicable to other communities and domains
